name: OpenGrinding
version: '1.0-SNAPSHOT'
main: nl.grapjeje.opengrinding.OpenGrinding
api-version: '1.21'
authors: [ GrapJeje ]
description: A grinding plugin for openMinetopia
website: grapjeje.nl

dependencies:
  server:
    OpenMinetopia:
      load: BEFORE
      required: true

commands:
  opengrinding:
    description: Credit command
  grindingregion:
    description: Region command
  sell:
    description: Sell command
