<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.grapjeje</groupId>
    <artifactId>opengrinding</artifactId>
    <version>1.0.0</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <groupId>nl.grapjeje.opengrinding.shared.version</groupId>
  <artifactId>v1_21_4</artifactId>
  <packaging>jar</packaging>

  <name>V1_21_4</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>nl.grapjeje.opengrinding</groupId>
      <artifactId>shared</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <version>1.21.4-R0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>

    <dependency>
      <groupId>nl.grapjeje</groupId>
      <artifactId>grapjeje-core</artifactId>
    </dependency>
  </dependencies>
</project>